### DISCUSSION TITLE
How to configure mutually exclusive pipelines in workflow?

### DISCUSSION THREAD

**Discussion by niconjjanssens** [ovh/cds#5649] [Q&A] [answered]
Hi,

I'm trying to configure a workflow, containing 2 pipelines that are mutually exclusive.
A simplified example to illustrate:
```yaml
name: TestMutualExclusive
version: v2.0
workflow:
  TstPip1:
    pipeline: TstPip1
  TstPip2_1:
    depends_on:
    - fork
    conditions:
      check:
      - variable: workflow.TstPip1.build.result
        operator: ge
        value: "1"
    pipeline: TestPip
  TstPip2_2:
    depends_on:
    - fork
    conditions:
      check:
      - variable: workflow.TstPip1.build.result
        operator: ge
        value: "2"
    pipeline: TestPip
  TstPip3:
    depends_on:
    - TstPip2_1
    - TstPip2_2
    pipeline: TestPip
```

When the pipeline (TstPip1) is executed the values (exported as variables using "worker export ...") are derived which drive the conditions for the middle pipelines (TstPip2_1 and TstPip2_2).  The issue is that TstPip3 is only executed, when both TstPip2_1 and TstPip2_2 are executed. But as soon as one of the middle pipelines is not executed  (nature of mutually exclusivity), TstPip3 is not executed, not even attempted. 

Any suggestions on how to configure such workflow?

Kr,
Nico
