### ISSUE TITLE
fix(sdk): imported key names are not checked for a valid name 

### ISSUE THREAD

**Issue by FabienM** [ovh/cds#2240]
`workflow push` and SDK allow this structure in a app yaml file:

```yaml
keys:
  ovhcli-git:
    type: ssh
  ovhcli-pgp:
    type: pgp
```

Names should be prefixed with`app-` and the import should fail.
