### ISSUE TITLE
Fix(keys): Keys without token in yaml are always regenerated on import

### ISSUE THREAD

**Issue by FabienM** [ovh/cds#2245]
Having such snippet in a `*.app.yml`:

```yaml
keys:
  app-ovhcli-git:
    type: ssh
  app-ovhcli-pgp:
    type: pgp
vcs_connection_type: ssh
vcs_ssh_key: app-ovhcli-git
vcs_pgp_key: app-ovhcli-pgp
```

Each time i WorkflowPush, new key pairs are generated until i complete the manifest with a value token:

```yaml
keys:
  app-ovhcli-git:
    type: ssh
    value: ad7afcf7081f4589ac23e2dba039ebb9
  app-ovhcli-pgp:
    type: pgp
    value: 4d8a3e52b9f14d88a730969ce4356932
vcs_connection_type: ssh
vcs_ssh_key: app-ovhcli-git
vcs_pgp_key: app-ovhcli-pgp
```

The problem is that at project creation I do not know the value token and i would like to avoid a new commit to update values after the first workflow push.
