### ISSUE TITLE
Enhancement: `workflow pull` should export `text` variables as multiline yaml

### ISSUE THREAD

**Issue by FabienM** [ovh/cds#2505]
I have a `text` variable that contains a large JSON (marathon configuration]. I would like to keep it versioned as multiline yaml:

```yaml
   marathon.config:
     type: text
    value: |
      {
        "id": "{{.cds.app.marathon.appID}}",
        "mem": 256,
        "cpus": 0.1,
        "instances": 1,
        "container": {
          "type": "DOCKER",
          "docker": {
            "network": "BRIDGE",
            "portMappings": [{
              "protocol": "tcp",
              "containerPort": 8081,
              "hostPort": 0
            }],
```

But `cdsctl workflow pull` keep onelining it:

```yaml
  marathon.config:
    type: text
    value: "{\n    \"id\": \"{{.cds.env.environment.prefix.deploy}}{{.cds.app.marathon.appID}}\",\n
      \   \"mem\": 256,\n    \"cpus\": 0.1,\n    \"instances\": 1,\n    \"container\":
      {\n        \"type\": \"DOCKER\",\n        \"docker\": {\n            \"network\":
      \"BRIDGE\",\n            \"portMappings\": [\n                {\n                    \"protocol\":
      \"tcp\",\n                    \"containerPort\": 8081,\n                    \"hostPort\":
```

Maybe multiline should be the default for `text`variables?
