### ISSUE TITLE
feat(scheduler): add pip params

### ISSUE THREAD

**Issue by blaryjp** [ovh/cds#2550]
Hello,

Can you please add the pip params when creating a scheduler ?

Thx

**Comment by blaryjp** [comment]
I definitely need this...

**Comment by yesnault** [comment]
already available. Example:

```yml
name: test-sche
version: v1.0
pipeline: with-pip
pipeline_hooks:
- type: Scheduler
  ref: with-pip.0
  config:
    cron: '* * * * *'
    payload: '{"toto":"a1"}'
    timezone: UTC
- type: Scheduler
  ref: with-pip.1
  config:
    cron: '*/2 * * * *'
    payload: '{"toto":"a2"}'
    timezone: UTC
```

with the pipeline:
```yml
version: v1.0
name: with-pip
parameters:
  aa:
    type: string
    default: '{{.toto}}'
jobs:
- job: New Job
  steps:
  - script:
    - env

```
