### ISSUE TITLE
WF as code doesn't export platform in pipeline context

### ISSUE THREAD

**Issue by FabienM** [ovh/cds#2697]
Given i added a platform to a pipeline context in a workflow, when i edit the workflow "as code" (in the UI or after a `workflow pull`, the platform doesn't appear in the exported pipeline context:

```yaml
  deploy:
    depends_on:
    - build-go
    conditions:
      script: return cds_manual == "true" or (cds_status == "Success" and git_branch
        == "master")
    when:
    - success
    pipeline: deploy
    application: MyApp
    environment: Playground.EU
    parameters:
      retry.delay.seconds: "5"
      retry.max: "30"
```
