### ISSUE TITLE
Workflow push won't save pipeline/platform associations

### ISSUE THREAD

**Issue by FabienM** [ovh/cds#2825]
```yml
  deploy-playground-eu:
    depends_on:
    - build-image-playground-eu
    when:
    - success
    pipeline: deploy-platform
    application: Lhasa
    platform: containers-dev
```

```
$ cdsctl workflow push URBA .cds/*.yml
$ git diff
```
```diff
diff --git a/.cds/LhasaWorkflow.yml b/.cds/LhasaWorkflow.yml
index fb7fd2b..08cde2f 100644
--- a/.cds/LhasaWorkflow.yml
+++ b/.cds/LhasaWorkflow.yml
@@ -50,7 +50,6 @@ workflow:
     - success
     pipeline: deploy-platform
     application: Lhasa
-    platform: containers-dev
```
