### ISSUE TITLE
pipeline parameter and default value

### ISSUE THREAD

**Issue by yesnault** [ovh/cds#3380]
workflow
```yml
name: testpip
version: v1.0
workflow:
  child:
    depends_on:
    - void
    when:
    - success
    pipeline: child
    parameters:
      foo: barAA
  void:
    pipeline: void
```

pipeline:
```yml
version: v1.0
name: child
parameters:
  foo:
    type: string
    default: bar
  foo2:
    type: string
    default: bar2
jobs:
- job: New Job
  steps:
  - script:
    - env
```

the pipeline parameter foo2 is not available in "Display job variables"

--> if the value of the parameter "foo" is equals to the default value, "foo2" is well available
