### ISSUE TITLE
outgoing hooks - 2 webhooks

### ISSUE THREAD

**Issue by yesnault** [ovh/cds#3479]
workflow:
```yml
name: outgoing7
version: v1.0
workflow:
  WebHook:
    depends_on:
    - env
    trigger: WebHook
  WebHook_1:
    depends_on:
    - env
    trigger: WebHook
  env:
    pipeline: env
```

pipeline:

```yml
version: v1.0
name: env
jobs:
- job: New Job
  steps:
  - script:
    - env
```

Run workflow - the webhook WebHook_1 is never launched
