### ISSUE TITLE
outgoing workflow hook - edit with ui

### ISSUE THREAD

**Issue by yesnault** [ovh/cds#3480]
workflow

```yml
name: outgoing8
version: v1.0
workflow:
  Workflow:
    depends_on:
    - env
    trigger: Workflow
    config:
      target_hook: 8c664eda-c9c1-41c8-8cac-0d0dbf3e4032
      target_project: 000AA
      target_workflow: echo
  env:
    pipeline: env
```

workflow & hook attribute are empty when we try to edit the outgoing hook

![capture d ecran 2018-10-19 a 16 57 05](https://user-images.githubusercontent.com/395454/47226127-0b34ee80-d3c0-11e8-9904-e7ee2fc8a14b.png)
