### ISSUE TITLE
renaming a node triggered after a join doesn't work

### ISSUE THREAD

**Issue by fsamin** [ovh/cds#3544]
```yaml
name: DDOS
version: v1.0
workflow:
  1_test-outgoing-hooks:
    pipeline: DDOS-me
    payload:
      plip: plop
  2_WebHook:
    depends_on:
    - 1_test-outgoing-hooks
    trigger: WebHook
    config:
      URL: a
      method: POST
      payload: '{}'
  2_after:
    depends_on:
    - 2_WebHook
    when:
    - success
    pipeline: DDOS-me
  3_Workflow:
    depends_on:
    - 1_test-outgoing-hooks
    trigger: Workflow
    config:
      target_hook: bd9ca90e-02e8-4559-9eca-9c56f1518945
      target_project: FSAMIN
      target_workflow: blabla
  3_after:
    depends_on:
    - 3_Workflow
    when:
    - success
    pipeline: DDOS-me
  4_end:
    depends_on:
    - 2_after
    - 3_after
    when:
    - success
    pipeline: DDOS-me
  "6_1":
    depends_on:
    - fork_1
    when:
    - success
    pipeline: DDOS-me
  "6_2":
    depends_on:
    - fork_1
    when:
    - success
    pipeline: DDOS-me
  fork_1:
    depends_on:
    - 4_end
metadata:
  default_tags: git.branch,git.author
```

try to rename nodes 6_1 or 6_2
