### ISSUE TITLE
Cannot create a workflow outgoing hook without payload

### ISSUE THREAD

**Issue by neyaled** [ovh/cds#4074]
When creating the workflow below, an error is thrown.

The error is:
Bad Request
Unable to update/delete the root node of your workflow

If the payload is set as '{}' the hook is created properly.

```
name: wf1
version: v1.0
workflow:
  Workflow:
    depends_on:
    - sleep-2s
    when:
    - success
    trigger: Workflow
    config:
      payload: ''
      target_hook: hook-id
      target_project: myproj
      target_workflow: wf2
  sleep-2s:
    when:
    - success
    pipeline: sleep-2s
```

Pipeline code:

```
version: v1.0
name: sleep-2s
jobs:
- job: sleep 2s
  steps:
  - script:
    - '#!/bin/bash'
    - ""
    - sleep 2
```
