### ISSUE TITLE
Propagation of workflow hook completion limited to one level

### ISSUE THREAD

**Issue by neyaled** [ovh/cds#4075]
If waterfalling workflows (wf1 -> wf2 -> wf3), the wf1 will never get the event of completion for the wf2. wf2 will be updated properly when wf3 completes.

wf1 code:
```
name: wf1
version: v1.0
workflow:
  Workflow:
    depends_on:
    - sleep-2s
    when:
    - success
    trigger: Workflow
    config:
      payload: '{}'
      target_hook: hook-id
      target_project: myproj
      target_workflow: wf2
  sleep-2s:
    when:
    - success
    pipeline: sleep-2s
```

wf2 code:
```
name: wf2
version: v1.0
workflow:
  Workflow:
    depends_on:
    - sleep-2s
    when:
    - success
    trigger: Workflow
    config:
      payload: |-
        {
        }
      target_hook: hook-id
      target_project: myproj
      target_workflow: wf3
  sleep-2s:
    pipeline: sleep-2s
hooks:
  sleep-2s:
  - type: Workflow
    ref: "ref1"
```

wf3 code:
```
name: wf3
version: v1.0
pipeline: sleep-2s
pipeline_hooks:
- type: Workflow
  ref: "ref2"
```

pipeline code:
```
version: v1.0
name: sleep-2s
jobs:
- job: sleep 2s
  steps:
  - script:
    - '#!/bin/bash'
    - ""
    - sleep 2
```
