### ISSUE TITLE
Migrate as code workflow with 2 hooks

### ISSUE THREAD

**Issue by sguiheux** [ovh/cds#4212]
When i migrate a workflow with 1 repo web hook + 1 web hook,  the web hook is not in the workflow file

**Comment by yesnault** [comment]
already fixed
```
name: test-migrate
version: v1.0
pipeline: env
payload:
  git.author: ""
  git.branch: master
  git.hash: ""
  git.hash.before: ""
  git.message: ""
  git.repository: ~YVONNICK.ESNAULT/foo
  git.tag: ""
application: foomigrate
pipeline_hooks:
- type: RepositoryWebHook
  ref: env.0
- type: WebHook
  ref: env.1
  config:
    method: POST
metadata:
  default_tags: git.branch,git.author
```
