### ISSUE TITLE
Bitbucket cloud: "Unable to decode key"

### ISSUE THREAD

**Issue by Mualig** [ovh/cds#4501]
I'm trying to configure bitbucket cloud as a repository manager (by following your [guide](https://ovh.github.io/cds/docs/integrations/bitbucketcloud/)) but I have an error when I'm trying to link my cds project to bitbucket (I'm disconnected from the UI) and I have the following error in the logs:
```
cds-vcs_1             | Starting service vcs
cds-vcs_1             | 2019-08-02 12:34:32 [INFO] vcs> Service registered
cds-vcs_1             | 2019-08-02 12:34:32 [INFO] VCS> Starting service vcs-service 0.40.0+cds.9951...
cds-vcs_1             | 2019-08-02 12:34:32 [DEBUG] VCS> Router initialized
cds-vcs_1             | 2019-08-02 12:34:32 [INFO] VCS> Starting HTTP Server on port 8084
cds-vcs_1             | 2019-08-02 12:34:51 [DEBUG] GET     |     124.138µs | /vcs
cds-vcs_1             | 2019-08-02 12:34:55 [WARN] requestToken>pprofLabel>recoverWrap>Handle>getAuthorizeHandler>AuthorizeRedirect>RequestToken>SignParams>sign: internal server error (caused by: Unable to decode key (length: 32))
cds-vcs_1             | 
cds-vcs_1             | 2019-08-02 12:34:55 [WARN] pprofLabel>recoverWrap>Handle>getAuthorizeHandler>AuthorizeRedirect>RequestToken>SignParams>sign: internal server error (caused by: bitbucket: Unable to get request token: Unable to decode key (length: 32)) error_uuid=eeeb0bd2-b521-11e9-9b4f-0242ac160005 method=GET request_uri=/vcs/bitbucket/authorize stack_trace=Unable to decode key (length: 32)
cds-vcs_1             | github.com/ovh/cds/sdk.WithStack
cds-vcs_1             | 	/go/src/github.com/ovh/cds/sdk/error.go:767
cds-vcs_1             | github.com/ovh/cds/engine/vcs/bitbucketserver.sign
cds-vcs_1             | 	/go/src/github.com/ovh/cds/engine/vcs/bitbucketserver/oauth_consumer_sign.go:80
cds-vcs_1             | github.com/ovh/cds/engine/vcs/bitbucketserver.(*bitbucketConsumer).SignParams
cds-vcs_1             | 	/go/src/github.com/ovh/cds/engine/vcs/bitbucketserver/oauth_consumer_sign.go:60
cds-vcs_1             | github.com/ovh/cds/engine/vcs/bitbucketserver.(*bitbucketConsumer).RequestToken
cds-vcs_1             | 	/go/src/github.com/ovh/cds/engine/vcs/bitbucketserver/oauth_consumer_token.go:173
cds-vcs_1             | github.com/ovh/cds/engine/vcs/bitbucketserver.(*bitbucketConsumer).AuthorizeRedirect
cds-vcs_1             | 	/go/src/github.com/ovh/cds/engine/vcs/bitbucketserver/oauth_consumer.go:17
cds-vcs_1             | github.com/ovh/cds/engine/vcs.(*Service).getAuthorizeHandler.func1
cds-vcs_1             | 	/go/src/github.com/ovh/cds/engine/vcs/vcs_handlers.go:278
cds-vcs_1             | github.com/ovh/cds/engine/api.(*Router).Handle.func1
cds-vcs_1             | 	/go/src/github.com/ovh/cds/engine/api/router.go:245
cds-vcs_1             | net/http.HandlerFunc.ServeHTTP
cds-vcs_1             | 	/usr/local/go/src/net/http/server.go:1995
cds-vcs_1             | github.com/ovh/cds/engine/api.(*Router).recoverWrap.func1
cds-vcs_1             | 	/go/src/github.com/ovh/cds/engine/api/router.go:152
cds-vcs_1             | net/http.HandlerFunc.ServeHTTP
cds-vcs_1             | 	/usr/local/go/src/net/http/server.go:1995
cds-vcs_1             | github.com/ovh/cds/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1
cds-vcs_1             | 	/go/src/github.com/ovh/cds/vendor/github.com/gorilla/handlers/compress.go:143
cds-vcs_1             | net/http.HandlerFunc.ServeHTTP
cds-vcs_1             | 	/usr/local/go/src/net/http/server.go:1995
cds-vcs_1             | github.com/ovh/cds/engine/api.(*Router).pprofLabel.func1
cds-vcs_1             | 	/go/src/github.com/ovh/cds/engine/api/router.go:89
cds-vcs_1             | net/http.HandlerFunc.ServeHTTP
cds-vcs_1             | 	/usr/local/go/src/net/http/server.go:1995
cds-vcs_1             | github.com/ovh/cds/vendor/github.com/gorilla/mux.(*Router).ServeHTTP
cds-vcs_1             | 	/go/src/github.com/ovh/cds/vendor/github.com/gorilla/mux/mux.go:114
cds-vcs_1             | net/http.serverHandler.ServeHTTP
cds-vcs_1             | 	/usr/local/go/src/net/http/server.go:2774
cds-vcs_1             | net/http.(*conn).serve
cds-vcs_1             | 	/usr/local/go/src/net/http/server.go:1878
cds-vcs_1             | runtime.goexit
cds-vcs_1             | 	/usr/local/go/src/runtime/asm_amd64.s:1337
cds-vcs_1             | Unable to get request token
cds-vcs_1             | bitbucket status=500
cds-vcs_1             | 2019-08-02 12:34:55 [DEBUG] GET     |    1.036753ms | /vcs/bitbucket/authorize
cds-vcs_1             | 2019-08-02 12:39:05 [DEBUG] GET     |     241.356µs | /vcs
```
I've successfully link my CDS to github, but not bitbucket or bitbucketCloud.
I'm using your docker-compose example with the following configuration for vcs (the key is no longer valid) :
```
  cds-vcs:
    image: ovhcom/cds-engine:latest
    command: sh -c "PATH=$PATH:/app /app/cds-engine-linux-amd64 start vcs"
    environment:
      CDS_LOG_LEVEL: debug
      CDS_VCS_NAME: vcs-service
      CDS_VCS_URL: http://cds-vcs:8084
      CDS_VCS_SERVERS_BITBUCKETCLOUD_BITBUCKETCLOUD_CLIENTID: HENXspXWS742EPac6s
      CDS_VCS_SERVERS_BITBUCKETCLOUD_BITBUCKETCLOUD_CLIENTSECRET: qXTm96bFB8rXANCJuYvN9uCbgS89bKhg
      CDS_VCS_API_TOKEN: changeitchangeitchangeitchangeitchangeitchangeitchangeitchangeit
      CDS_VCS_API_HTTP_URL: http://cds-api:8081
      CDS_VCS_API_GRPC_URL: http://cds-api:8081
      CDS_VCS_CACHE_REDIS_HOST: cds-cache:6379
      CDS_VCS_CACHE_REDIS_PASSWORD: cds
    ports:
      - "8084:8084"
    links:
       - cds-api
       - cds-cache
```
I'll appreciate any help.
