### ISSUE TITLE
CDS webhook fails with createOperationRequest: branch parameter is mandatory

### ISSUE THREAD

**Issue by AndrzejA35** [ovh/cds#4534]
Hello,

Basically, I have created two workflows. They are almost the same. The main difference is that first is stored in the repository (workflow imported from a repository), second has been created in UI. I have also defined two push webhooks in the Bitbucket server. One for each of the workflows. A workflow created in the UI seems to be working fine (is triggered by webhook test and by pushing a commit to Bitbucket), however workflow imported from a repository is failing due to a:

```
[ERROR] unable to start workflow: GoRoutine>postWorkflowRunHandler>initWorkflowRun>CreateFromRepository>createOperationRequest: wrong request (caused by: unable to get workflow from repository.: Unable to create operation request: createOperationRequest: branch parameter is mandatory)
```

Could you advise on this issue? I'm more interested in having workflow imported from .yml files working than the one created in UI. 
Hopefully, all the necessary details have been posted below:

**Workflow and application imported from repository look like this:**

```
name: cds-pipeline
version: v1.0
pipeline: build-pipeline
payload:
  git.branch: master
  git.repository: POC/cds-pipeline
application: cds-pipeline-app
pipeline_hooks:
- type: WebHook
  ref: "1234509876"
  config:
    method: POST
metadata:
  default_tags: git.branch,git.author
```
```
version: v1.0
name: cds-pipeline-app
vcs_server: bitbucket 
repo: POC/cds-pipeline
vcs_connection_type: ssh
vcs_ssh_key: proj-ssh-poc
vcs_pgp_key: proj-pgp-poc
```

**Workflow and application created in UI look like this:**
```
name: TEST
description: "This Workflow has been created through the gui entirely. \nIt doesn't
  require repository interaction, thus it serves learning purposes effectively. "
version: v1.0
pipeline: TEST
payload:
  git.author: ""
  git.branch: master
  git.hash: ""
  git.hash.before: ""
  git.message: ""
  git.repository: POC/cds-pipeline
  git.tag: ""
application: TEST
pipeline_hooks:
- type: WebHook
  ref: "1565977314"
  config:
    method: POST
metadata:
  default_tags: git.branch,git.author
```
```
version: v1.0
name: TEST
vcs_server: bitbucket
repo: POC/cds-pipeline
vcs_connection_type: ssh
vcs_ssh_key: proj-ssh-poc
vcs_pgp_key: proj-pgp-poc
```
