### ISSUE TITLE
first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by icarrr** [ovh/cds#4696]
I have set up SMTP in the conf.toml file, after running the cds API, I checked the status, instead got this and the cds couldn't send email.
```json
{
  "status": "AL",
  "component": "SMTP Ping",
  "value": "KO: tls: first record does not look like a TLS handshake",
  "type": ""
}
```

I use the Sendgrid SMTP API.

**Comment by yesnault** [comment]
Hi @icarrr. Which port do you use on sendgrid?

**Comment by icarrr** [comment]
@yesnault I'm using port 587 for TLS

**Comment by yesnault** [comment]
@icarrr 

Example that works with sendgrid (you need just to replace password value)

```toml
[api.smtp]
    disable = false
    from = "no-reply@cds.local"
    host = "smtp.sendgrid.net"
    password = "your-very-long-password"
    port = "465"
    tls = true
    user = "apikey"
```
