### ISSUE TITLE
hooks: ref is a bad idea

### ISSUE THREAD

**Issue by fsamin** [ovh/cds#4858]
Hooks Ref should not be a business property.
It is only a technical property that help us to identify hooks.

this is boilerplate in as-code format and it can do very strange behavior with as-code workflow:

example:

```yaml
name: xxx
version: v1.0
workflow:
  xxx:
    pipeline: xxx
    application: xxx
    notify:
    - type: vcs
hooks:
  xxx:
  - type: Scheduler
    ref: xxx.0
    config:
      cron: 0/15 * * * *
      payload: '{}'
      timezone: UTC
```

generates this configuration:

```yaml
name: xxx
version: v1.0
pipeline: xxx
payload:
  git.author: ""
  git.branch: master
  git.hash: ""
  git.hash.before: ""
  git.message: ""
  git.repository: xxx/xxx
  git.tag: ""
application: xxx
pipeline_hooks:
- type: Scheduler
  ref:xxx.0
  config:
    cron: 0/15 * * * *
    payload: |-
      {
        "git.author": "",
        "git.branch": "master",
        "git.hash": "",
        "git.hash.before": "",
        "git.message": "",
        "git.repository": "xxx/xxx",
        "git.tag": ""
      }
    timezone: UTC
- type: RepositoryWebHook
  ref: xxx.0
```

we have two hooks with the same ref, the result is unpredictable behavior, like randomly stopping the scheduler.

the "ref" is useful but should be function of the type, pipeline and configuration of the hook and not an attribute

finally it should not be exported in as-code format
