### ISSUE TITLE
npm-audit-parser fail to start

### ISSUE THREAD

**Issue by Mualig** [ovh/cds#4871]
Hi,

I'm trying to use the npm-audit-parser plugin in a node-10 worker started by a swarm hatchery, but the step always fails (permission denied, but the user is root). Am I missing some configuration somewhere to use this plugin ?
```
Starting step "/plugin-npm-audit-parser-5"
Unable to start grpc plugin... Aborting (GoRoutine: internal server error (caused by: plugin:plugin-npm-audit-parser unable to start GRPC plugin, binary command not found.: exec: "/tmp": permission denied))
End of step "/plugin-npm-audit-parser-5" [Fail] with reason: Unable to start grpc plugin... Aborting (GoRoutine: internal server error (caused by: plugin:plugin-npm-audit-parser unable to start GRPC plugin, binary command not found.: exec: "/tmp": permission denied))
```
The plugin is on the worker (I've added a script step before the plugin):
```
ls -l /tmp
total 17056
drwxr-xr-x 4 root root     4096 Jan  8 10:34 Sm9iIDE
-rwxr-xr-x 1 root root       27 Jan  8 10:34 cds-306103024
-rwxr-xr-x 1 root root 17455068 Jan  8 10:34 npm-audit-parser-linux-amd64
```

Here is my pipeline configuration:
```
version: v1.0
name: Pipeline-1
jobs:
- job: Job 1
  steps:
  - checkout: '{{.cds.workspace}}'
  - name: npm install
    enabled: false
    script:
    - npm install --no-audit
  - name: npm audit
    optional: true
    script:
    - npm audit --json > report.json
  - script:
    - ls -l /tmp
  - plugin-npm-audit-parser:
      file: '{{.cds.workspace}}/report.json'
  requirements:
  - binary: git
  - plugin: plugin-npm-audit-parser
```

The binary comes from the github release and was imported with the cdsctl:
```
./cdsctl admin plugins list
+--------------------------------+--------------------------------+----+-------------+-------------------------+--------+
|             AUTHOR             |          DESCRIPTION           | ID | INTEGRATION |          NAME           |  TYPE  |
+--------------------------------+--------------------------------+----+-------------+-------------------------+--------+
| Steven GUIHEUX                 | This is a plugin to parse npm  |  2 |             | plugin-npm-audit-parser | action |
| <steven.guiheux@corp.ovh.com>  | audit report                   |    |             |                         |        |
+--------------------------------+--------------------------------+----+-------------+-------------------------+--------+
```
