### ISSUE TITLE
Volume requirement export doesn't work for pipeline.

### ISSUE THREAD

**Issue by AndrzejA35** [ovh/cds#4879]
Hello,

I tried to export the volume requirement for a pipeline. It seems this functionality does not work. 

Requirements in my pipeline configuration (created manualy):
![Screenshot from 2020-01-11 19-32-55](https://user-images.githubusercontent.com/7427700/72209517-7da35a00-34af-11ea-81b4-fcee7ccadf19.png)

Edit as code does not output volume requirement:
![Screenshot from 2020-01-11 19-33-08](https://user-images.githubusercontent.com/7427700/72209519-7da35a00-34af-11ea-9647-08099197169d.png)

Also for testing purpose, I tried to import pipeline with this as requirements:
```
requirements:
  - binary: docker
  - binary: git
  - binary: gpg
  - volume: type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock
```
but it failed:
![Screenshot from 2020-01-11 19-32-43](https://user-images.githubusercontent.com/7427700/72209761-471b0e80-34b2-11ea-9f9e-839f9f4f6161.png)

can anyone look at it?
