### ISSUE TITLE
Can't import a repository. Throws "invalid hook configuration"

### ISSUE THREAD

**Issue by nielsonsantana** [ovh/cds#5143]
Firstly, thanks to make this awesome CI/CD tools available. 
I'm trying CDS however I getting this error.
**cds version:** ovhcom/cds-engine:0.45.2

![Screenshot from 2020-04-23 02-18-35](https://user-images.githubusercontent.com/627596/80064600-ce930780-850e-11ea-84a4-daa41d72b5a1.png)

I tried diferents setups with hooks as `WebHook`, `RepositoryWebHook`, `Git Repository Poller` and none worked.

My Workflow:
```yaml
name: cdsminimal
version: v1.0
workflow:
  build:
    pipeline: minimal-pipeline
    application: minimal-app
    payload:
      git.author: ""
      git.branch: master
      git.hash: ""
      git.hash.before: ""
      git.message: ""
      git.repository: nielsonsantana/cdsminimal
      git.tag: ""
  build2:
    depends_on:
    - build
    when:
    - success
    pipeline: minimal-pipeline
    application: minimal-app
hooks:
  build:
  - type: WebHook
    config:
      method: POST
  - type: RepositoryWebHook
  - type: Git Repository Poller
    config:
      payload: '{}'
metadata:
  default_tags: git.branch,git.author
```
Application
```yaml
version: v1.0
name: minimal-app
vcs_server: github
repo: nielsonsantana/cdsminimal
vcs_branch: '{{.git.branch}}'
vcs_default_branch: master
vcs_connection_type: ssh
vcs_ssh_key: proj-ssh-cdshello
```
minimal-pipeline
```yaml
version: v1.0
name: minimal-pipeline
jobs:
- job: First job
  steps:
  - checkout: '{{.cds.workspace}}'
  - script: echo "Hello World"
  requirements:
  - binary: git

```

**Traceback**
```bash
2020-04-23 05:56:22 [INFO] pprofLabel>compress>recoverWrap>Handle>postPerformImportAsCodeHandler>Push>ParseAndImport>Import>Insert>hookRegistration>
createVCSConfiguration: Invalid hook configuration (caused by: Unable to push workflow: unable to import workflow cdsminimal: 
Unable to insert workflow: Cannot create vcs configuration: wrong webHookURL value (project: CDSMINIMAL, repository: nielsonsantana/cdsminimal)) 
auth_consumer_id=e69db7b5-8900-42a8-a8d3-20f846c6be29 auth_session_id=80076b78-12b8-40ee-8cde-86c4e3fbe8ba 
auth_user_id=663e0366-ea7a-4a16-aa2e-4130168abd19 request_id=0d904fb2-6697-425f-83ac-39540623eb0e 
stack_trace=wrong webHookURL value (project: CDSMINIMAL, repository: nielsonsantana/cdsminimal)
github.com/ovh/cds/sdk.WrapError
	/tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/sdk/error.go:771
github.com/ovh/cds/engine/api/workflow.createVCSConfiguration
	/tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/workflow/hook.go:297
github.com/ovh/cds/engine/api/workflow.hookRegistration
	/tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/workflow/hook.go:184
github.com/ovh/cds/engine/api/workflow.Insert
	/tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/workflow/dao.go:679
github.com/ovh/cds/engine/api/workflow.Import
	/tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/workflow/workflow_importer.go:33
github.com/ovh/cds/engine/api/workflow.ParseAndImport
	/tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/workflow/workflow_parser.go:192
github.com/ovh/cds/engine/api/workflow.Push
	/tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/workflow/dao.go:1482
github.com/ovh/cds/engine/api.(*API).postPerformImportAsCodeHandler.func1
	/tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/ascode.go:151
github.com/ovh/cds/engine/api.(*Router).Handle.func1
	/tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/router.go:409
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2007
github.com/ovh/cds/engine/api.(*Router).recoverWrap.func1
	/tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/router.go:162
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2007
github.com/gorilla/handlers.CompressHandlerLevel.func1
	/go/pkg/mod/github.com/gorilla/handlers@v0.0.0-20160816184729-a5775781a543/compress.go:143
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2007
github.com/ovh/cds/engine/api.(*Router).compress.func1
	/tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/router.go:100
github.com/ovh/cds/engine/api.(*Router).pprofLabel.func1
	/tmp/QnVpbGQgYW5kIFBhY2thZ2UgQWxs/run/engine/api/router.go:92
net/http.HandlerFunc.ServeHTTP
	/usr/local/go/src/net/http/server.go:2007
github.com/gorilla/mux.(*Router).ServeHTTP
	/go/pkg/mod/github.com/gorilla/mux@v1.6.2/mux.go:162
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:2802
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:1890
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
Cannot create vcs configuration
Unable to insert workflow
unable to import workflow cdsminimal
Unable to push workflow

```
