### ISSUE TITLE
Check property ok with UI but not with as code

### ISSUE THREAD

**Issue by marie-j** [ovh/cds#5796]
Hello, 

When trying to edit as code a workflow, there is an error saying `additionalProperty "check"  exists in instance when not allowed` which prevents from doing anything with as code.
However if we go through UI and "Edit the context" it works and the `check` property is generated automatically in the as code

Example :
```yaml
  pipeline:
    conditions:
      check:
      - variable: cds.manual
        operator: eq
        value: ""
```
