### ISSUE TITLE
Requirements with a specific worker model and a service

### ISSUE THREAD

**Issue by b2p-fred** [ovh/cds#5985]
I am trying to create a pipeline where my tests require to use some external services (e.g. database, Redis, ...).

I created a service requiring a worker model and 3 services:
```
version: v1.0
name: deploy-backend
description: Deploy the application backend
jobs:
- job: Setup the application package
  steps:
  - script:
    - curl -v -X GET http://my_nginx
  requirements:
  - model: eprotocole/epr-PHP
  - service:
      name: my_nginx
      value: nginx:1.11.1
  - service:
      name: my_pg
      value: postgres:9.5.3 POSTGRES_USER=myuser POSTGRES_PASSWORD=mypassword
  - service:
      name: my_redis
      value: redis:6.2.6
```

When I run a workflow including my `deploy-backend` pipeline, the result is:
```
Informations
✓ Job has been queued
2021-10-25 02:33:21 +02:00 Hatchery cds-hatchery-swarm-cdsinte starts spawn worker with model eprotocole/epr-PHP
2021-10-25 02:33:22 +02:00 Hatchery cds-hatchery-swarm-cdsinte starts docker pull redis:6.2.6...
2021-10-25 02:33:26 +02:00 ⚠ Hatchery cds-hatchery-swarm-cdsinte - docker pull redis:6.2.6 done with error: internal server error
2021-10-25 02:33:27 +02:00 Error while Hatchery cds-hatchery-swarm-cdsinte spawns worker with model eprotocole/epr-PHP after 4s, err:internal server error
2021-10-25 02:33:27 +02:00 The pipeline has been stopped by fmohier
```
It is not able to get the Docker image for the Redis service. One should note that there was no problem with the nginx and postgresql docker images ...

I tried with : 
 - different Docker images, 
 - different tags
 - different tags for nginx and postgresql
 but I always have the same problem ... it looks like only the nginx and postgresql that  are used as [samples in the tutorials doc](https://ovh.github.io/cds/docs/tutorials/service-requirement-pg/) are accepted !

What about this ?

**[Edit]** After some more investigation I found out that the images used as a service are not pulled  because of a refused authentication ...

```
2021-10-25 14:24:13 [ERROR] hatchery cds-hatchery-swarm-cdsinte cannot spawn worker eprotocole/epr-PHP for job 4563: Exec>startWorkerStarters>workerStarter>spawnWorkerForJob>SpawnWorker>createAndStartContainer>pullImage: internal server error (caused by: Unable to pull image redis:6.2.6 on sample-docker-engine: Error response from daemon: Head https://registry-1.docker.io/v2/library/redis/manifests/6.2.6: unauthorized: incorrect username or password) caller=github.com/ovh/cds/sdk/hatchery.spawnWorkerForJob goroutine=workerStarter-8 service=hatchery:swarm source_file=/tmp/790ad7b9a1a85167593986ed564384b7/run/sdk/hatchery/starter.go source_line=208 stack_trace=Error response from daemon: Head https://registry-1.docker.io/v2/library/redis/manifests/6.2.6: unauthorized: incorrect username or password
```

 where should I define the credentials for this authentication ?
