### ISSUE TITLE
Worker model capabilities - discovery does not always have the same result

### ISSUE THREAD

**Issue by b2p-fred** [ovh/cds#6006]
I declared a worker model as is:
```
name: docker-compose-git
group: shared.infra
image: youpy/docker-compose-git
description: Docker alpine with Docker and Docker compose
type: docker
envs:
  CDS_GRAYLOG_EXTRA_KEY: '{{.GraylogExtraKey}}'
  CDS_GRAYLOG_EXTRA_VALUE: '{{.GraylogExtraValue}}'
  CDS_GRAYLOG_HOST: '{{.GraylogHost}}'
  CDS_GRAYLOG_PORT: '{{.GraylogPort}}'
  CDS_SINGLE_USE: "1"
  CDS_TTL: '{{.TTL}}'
shell: sh -c
cmd: apk add curl && curl ${CDS_API}/download/worker/linux/$(uname -m) -o worker --retry 10 --retry-max-time 120 && chmod +x worker && exec ./worker
```

And I expect that CDS will discover **docker**, **docker-compose** and **git** as available binaries but I only get **docker** and **git** !

I do not know if it will help but I am using a local 0.49 installation based on docker-compose with a swarm hatchery. Note that the same worker model imported in a 0.48 discovered the expected binaries.
