### ISSUE TITLE
Cannot edit pipeline context through the UI

### ISSUE THREAD

**Issue by MaximeWeyl** [ovh/cds#6054]
When a pipeline is already in my workflow, I cannot edit the context (application of the pipeline for instance) through the UI.
The dropdown seems broken (it pops up and closes immediately), and even if I try to type from Keyboard, nothing is taken into account.
Here is a video of this behaviour: https://www.youtube.com/watch?v=mW7BtuzjMMA

CDS version : 

```
cdsctl version
cdsctl:
  version: 0.49.0-99-gc44b723d8.16598
  architecture: amd64
  os: darwin
  git_hash: c44b723d8c172e739f36c2ea47abb1185b89f37a
  build_time: 10/06/21-14:55:28
  keychain: true
api:
  version: 0.49.0-172-g0cbd7852d.16974
  architecture: amd64
  os: linux
  git_hash: 0cbd7852d75805cdac746c267148cd1c99a00af9
  build_time: 01/10/22-10:23:20
  db_migrate: "0"


```
