### ISSUE TITLE
[Question] Inner job hook feature

### ISSUE THREAD

**Issue by killzoner** [ovh/cds#6059]
Hi there, 

I am investigating using CDS to handle workflows with tasks executed outside of workers.
Imagine I have this schema for a workflow

```yaml
  - task 1: trigger job using webhook from API A
  - task 2: trigger job using webhook from API B

  - task 3: output ok if task1 AND task2 reported OK
```

I would need some inner workflow hook available to report from the outside system that the job is OK or KO.
Is there such a capability in the REST API ? Couldn't determine it (saw workflow hooks to trigger one but nothing similar to what i'm searching).

If there is another way to do that using CDS, please feel free to suggest

Thanks in advance
