### ISSUE TITLE
UI metrics missing

### ISSUE THREAD

**Issue by kovacsur** [ovh/cds#6168]
We tried to implement metrics collection on a CDS instance. Documentation is unfortunately lacking in this respect. It was our impression that metrics data should be exposed on the endpoint /mon/metrics which appears to be working on most components (API, hooks, etc.), but not on UI, which returns

`{"id":38,"message":"resource not found","request_id":"9483067c-6d92-44ad-acd4-678a4b47a681"}`

Should we be able to get metrics info from the UI component or is this intended?

**Comment by martikan** [comment]
Hello @yesnault 

This is a log from the CDS UI service.

[cds_logs_20220912.txt](https://github.com/ovh/cds/files/9548924/cds_logs_20220912.txt)

The HTTP response has been the same as @kovacsur :
`{
    "id": 38,
    "message": "resource not found",
    "request_id": "bd9f02e4-15e8-40e0-ae0d-9f35d7c5e3bf"
}`

**Comment by yesnault** [comment]
Do you have something like that configured in your `ui` service ?

```toml
[telemetry]
  metricsEnabled = true
  tracingEnabled = true

  [telemetry.Exporters]

    [telemetry.Exporters.Jaeger]
      HTTPCollectorEndpoint = "https://your-jaeger-server:12345"
      collectorEndpoint = "https://your-jaeger-server:12345/api/traces"
      samplingProbability = 0.25
      serviceName = "Your-Team-Service-Here"

    [telemetry.Exporters.Prometheus]
      ReporteringPeriod = 10
```
Feel free to reopen if needed.
